services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moneywise-app
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DOCKER_DB_HOST}:${DOCKER_DB_PORT}/${DB_NAME}
    depends_on:
      - db_container
      - mailpit
    networks:
      - moneywise-network
    command: >
      sh -c "bash ./wait-for-it.sh ${DOCKER_DB_HOST}:${DOCKER_DB_PORT} -- flask db upgrade && python app.py"
    volumes:
      - .:/app

  db_container:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PUBLIC_PORT}:${DOCKER_DB_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - moneywise-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: moneywise-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-${MAIL_DEFAULT_SENDER}}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-${DB_PASSWORD}}
    ports:
      - "5050:80"
    depends_on:
      - db_container
    networks:
      - moneywise-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  mailpit:
    image: axllent/mailpit:latest
    container_name: moneywise-mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - moneywise-network

  jenkins:
    image: jmsz1/moneywise-jenkins:latest # trocar por 'build:' abaixo caso precise modificar o jenkins
    # build:
    #   context: .
    #   dockerfile: Dockerfile.jenkins
    container_name: moneywise-jenkins
    user: root
    environment:
      DOCKERHUB_IMAGE: ${DOCKERHUB_IMAGE:-}
      DOCKERHUB_CREDENTIALS_ID: ${DOCKERHUB_CREDENTIALS_ID:-dockerhub-credentials}
      NOTIFICATION_EMAIL: ${NOTIFICATION_EMAIL:-}
      NOTIFICATION_FROM: ${NOTIFICATION_FROM:-}
      MAIL_SERVER: ${MAIL_SERVER:-}
      MAIL_PORT: ${MAIL_PORT:-}
      MAIL_USE_TLS: ${MAIL_USE_TLS:-}
      MAIL_USE_SSL: ${MAIL_USE_SSL:-}
      MAIL_USERNAME: ${MAIL_USERNAME:-}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-}
      MAIL_DEFAULT_SENDER: ${MAIL_DEFAULT_SENDER:-}
      MAIL_CONTACT_RECIPIENT: ${MAIL_CONTACT_RECIPIENT:-}
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_PORT: ${SMTP_PORT:-}
      SMTP_USE_TLS: ${SMTP_USE_TLS:-}
      SMTP_USE_SSL: ${SMTP_USE_SSL:-}
      SMTP_USERNAME: ${SMTP_USERNAME:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
    depends_on:
      - mailpit
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      # - /run/user/1000/docker.sock:/var/run/docker.sock # se docker rodar em modo rootless, usar esse volume e comentar volume acima
    networks:
      - moneywise-network

volumes:
  db-data:
  jenkins-data:
  pgadmin-data:

networks:
  moneywise-network:
    driver: bridge
